### ISSUE TITLE
time of day distribution for crossfilter example is wrong

### ISSUE THREAD

**Issue by espinielli** [vega/vega-editor#2]
time of day distribution for crossfilter example is not the same as in [crossfilter site](http://square.github.io/crossfilter/).
I was trying to learn more trying to find how `hours` is defined but gave up and just tried to shift to match:
It would be ok if for the data transform for the hour field you use the expression   `(hours(datum.date)+15)%24` instead of `hours(datum.date)`.
(which probably does not make any sense from the data values...flight times should be in utc, shouldn't they?)

**Comment by arvind** [comment]
Hi @espinielli, I'm not able to see much of a difference between the two examples. Do you mind posting a screenshot of the behaviour you're seeing? I wonder if timezones are affecting something. Also, it's worth mentioning that our (Vega) example uses a random 2,000 point sample of the original 203,000 point data set. So you're likely to see significant differences in data distributions once you start brushing.

**Comment by espinielli** [comment]
@arvinf, the Time of Day distribution should show that the vast majority of flights is flying during the day: this is typical of commercial flights (DHL & Co. usually fly more during the night when costs/charges are lower and there are no passengers involved...)

That is what triggered my surprise in Vega Editor's rendering of Crossfilter's example (even [random] sampling of the original dataset should have maintained a marked split day/night...so I suspect the source is something else...)

Here are the screenshots (I did not apply any filtering, the screenshots are taken just out of initial rendering):
Original Crossfilter:
![image](https://cloud.githubusercontent.com/assets/891692/8698428/808745de-2afe-11e5-8d05-a17b3f0ee8c3.png)

and the one from Vega Editor:
![image](https://cloud.githubusercontent.com/assets/891692/8698444/96554ad2-2afe-11e5-80bd-bae3bbac7c9f.png)

HTH
Ciao

**Comment by arvinf** [comment]
@espinielli -- wrong person ;). You want @arvind.

**Comment by arvind** [comment]
@espinielli And what time zone are you currently in?

**Comment by arvind** [comment]
Aha, caught the error. In my sampling script, I was converting the original datetime into a local datetime. Should be resolved with d25e931. Thanks for filing the bug!

**Comment by espinielli** [comment]
@arvind did you sample the original dataset to keep the (web-based vega editor) example small and fast to load (and still representative) or is there a big performance problem in rendering the biggish original dataset via Vega?

**Comment by arvind** [comment]
Both. Crossfilter is a special-purpose library which builds special indexing data structures to get fast interactive performance. As a general-purpose library, Vega is slower at executing such queries with the original 200k dataset.

However, Vega's data transformation pipeline is extensible. A plugin could be written which builds the same data structures as Crossfilter but integrates them within the Vega framework.

**Comment by espinielli** [comment]
It looks like this bug is back...I get low numbers of flight in the interval 9-14.
![screen shot 2015-11-24 at 10 58 56 am](https://cloud.githubusercontent.com/assets/891692/11363882/deb6fcde-929c-11e5-92ac-de6db64bbca5.png)
